var questions = [
    ["The day on which the Sun's direct rays cross the celestrial equator is called?","Equinox","Ecliptic","Solstice","Easter","1"],
    ["What is the biggest sea on Earth?"," Black Sea","Red sea","Caspian sea","baltic sea","3"],
    ["What is RED-LIST?","List of extinct species","List of new species","List of hybrid species","List of endangered species","4"],
    ["In the food chain 'grass --> grasshopper --> frog --> snake --> eagle', what organism is the producer?","Grasshopper","Grass","Snake","Frog","2"],
    ["What is the name of NASA's most famous space telescope that is reflector type?","Hubble space telescope","Kepler space telescope","Spitzer space telescope","James Webb space telescope","1"],
    ["A group of stars forming a traditionally recognized patters is called?","Cluster of stars","Nebula","Constellations","Galaxy","3"],
    ["Which way does Earth spin?","West to East","East to West","Depends on Sun's direction","North to South","1"],
    ["How many hearts does an octopus have?","4","1","3","8","3"],
    ["What type of cell does not have a proper nucleus?","Eukaryotic cells","Red Blood Cells","Prokaryotic cells","Plant cell","3"],
    ["Why earth is much warmer than the rest of the space?","Because of magma inside earth","Because of sun","Water vapor, carbon di oxide and other gases radiates the heat from sun","None","3"],
    ["Who was the first person planned to reach India?","Christopher Columbus","Vasco-da-gama","Francis Drake","Amerigo Vespucci","2"],
    ["Who is the largest employer in India","speed post","Tata group","Indian railways","Reliance group","3"],
    ["India has the largest number of ____________","post office","railway lines","Airports","bus terminals","1"],
    ["Science day in Switzerland is dedicated to which of the following Indian","Sir.C.V. Raman","Sarvepalli Radhakrishnan","APJ Abdul Kalam","Ramanujam","3"],
    ["Which among these is the most visited place in the India?","Tirupati","Golden Temple","Taj Mahal","Mumbai","3"],
    ["Shakuntala Devi was rewarded with the title of","Mathematical Mastermind","Shakespeare of India","Great Warrior","The Human Calculator","4"],
    ["Which among the following in body grows faster?","NAILS","BONE MARROW","SKIN","HAIR","2"],
    ["Which is the largest organ of human body?","Liver","Intestine","Skin","Skeleton","3"],
    ["What is the name of Indian National flag?","Tirvarna","Tiranga","Saffron","Tribarna","2"],
    ["Who designed the present National Flag of India?","Sachindra Prasad Bose","Sukumar Mitra","Sarojini Naidu","Pingali Venkaiya","4"],
];